### ISSUE TITLE
Failure when inner loop references not-yet-parsed field from outer loop

### ISSUE THREAD

**Issue by dnault** [couchbaselabs/gojsonsm#9] opened 2018-07-17 22:17 UTC
Given this JSON document:
```
{
  "foo": [
    {
      "bar": [1, 2, 3],
      "zot" : 2
    }
  ]
}
```

The following match expression fails because `zot` appears in the JSON *after* `bar`, and the code that defers loop evaluation only looks for fields rooted at $doc (ignores fields rooted at outer loops).

```
any $f in $doc.foo {
    any $b in $f.bar {
        $f.zot == $b
    }
}
```

**Comment by brett19** [comment] 2018-08-03 11:16
Closing this as a duplicate of #5

**Closed by brett19** 2018-08-03 11:16 UTC
Labels: bug, duplicate
